### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by brianteeman** [alexandreelise/j4x-api-collection#1]
hi. thanks for creating this collection.

unfortunately i am getting a format not recognised message when trying to import it.

if i run the collection through a json linter https://jsonlint.com/ it shows the following error

```
Error: Parse error on line 3048:
...fileBehavior": {}} {	"info": {		"_pos
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'
```

**Comment by alexandreelise** [comment]
Hi @brianteeman,
Thanks for reporting this issue. I was too eager to share this with the joomla community and I posted too quickly. In fact I copied my local collection twice in this repo. That's why there is the error you mentioned. The file should be 3137 lines long not over 6000 lines. I tested the new file merged in master directly and now it works fine hopefully. Thanks again for your help. I am willing to share and be more involved in the Joomla! community I am active in joomla.stackexchange.com and also on my blog alexandre-elise.fr talking about Joomla!  I just can't stop talking about joomla because I love it so much and I can't stand when people unaware with joomla awesome power bragging about it without having using joomla at least once.   I have another repo you might have a look. It's COOPACL a system plugin cooperating with joomla core acl and add user based access level  to joomla 3. It can also do both without hacking core files. Just with a system plugin. 
Take care brian and have a nice day. 
Thanks again.

**Comment by alexandreelise** [comment]
I'm closing this issue as it works fine now. Take care.

**Comment by brianteeman** [comment]
Thanks for the speedy fix. I'm still learning postman otherwise I would have tried to debug the issue myself.

There are always lots of things to do to make joomla even more amazing. 

I saw your coooacl announcement but as I don't really use any ACL it wasn't relevant to me BUT it's on my list of things to check out when I find a spare moment.

**Comment by alexandreelise** [comment]
@brianteeman No problem. Take your time. I'll try to work on blocking issues for Joomla 4 on my spare time to help the Joomla 4 addicts and the joomla community overall and get Joomla 4 ready as quick as possible. It's on my TODO list.
Best regards
