### ISSUE TITLE
JSON body raw error

### ISSUE THREAD

**Issue by bato3** [alexandreelise/j4x-api-collection#12]
JSON spec told, that parameters should be double-quoted. But there are libraries, then allow to handle this (eg. json5), but please fix this...

[` : 'Here's an article'}`](https://github.com/alexandreelise/j4x-api-collection/blob/master/src/js/api.json#L1093)

Did you see 3x `'` and any escape character

**Comment by alexandreelise** [comment]
Hi @bato3   Thanks for reporting this issue. It has been fixed. One suggestion though. Use the collection rather than the api.json. I deleted it to avoid confusion.
Here is the link to the  [Joomla! 4 Web Services Postman Collection](https://github.com/alexandreelise/j4x-api-collection/blob/master/j4x-api-complete-collection.postman_collection.json)
