### ISSUE TITLE
Invalid json

### ISSUE THREAD

**Issue by brianteeman** [alexandreelise/j4x-api-collection#3]
After importing the collection I am getting invalid json errors for all the body data.

If I compare the body data that doesn't work
https://github.com/alexandreelise/j4x-api-collection/blob/05f2c6ff93ed2422419d5a544636046e9879c51f/j4x-api-complete-collection.postman_collection.json#L1205-L1208

With an export that does work it looks like your collection is not using escaped quotes and is missing the json option. This is what I get

```
				"body": {
					"mode": "raw",
					"raw": "{\"catid\": 64,\"title\": \"Updated article\"}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
```

**Comment by alexandreelise** [comment]
Hi,
Thanks for reporting this issue. In order to extract the joomla 4 API from the spec. I used a tool provided by one of the postman staff on their forum. It was a lot of work to fix the bugs. I try to do my best to make it work. I think the right thing to do is to import the collection and export it back from postman to have the right format. Hope it helps. Sorry for the inconvience.

**Comment by alexandreelise** [comment]
Hello @brianteeman,
I just exported from postman and verified the resulting json using the tool you suggested "jsonlint.com" and now it is valid. I am closing this issue for now. Feel free to comment or give your feedback. Thanks again. Have a nice day.
